# 运行说明：
# 在目标服务器上，建立一个xyz-chat文件夹
#   在里面放入：本文件（docker-compose.yml）, .env file
# 先登录docker registry：
#  docker login https://registry.ware.cloud
#   shawn / Tu3eib9pOBm2er7u
# 
# 启动服务：
# docker-compose up -d 启动服务（自动拉取xyzchat:latest）
# export APP_VERSION=1.0.1 && docker-compose up -d 启动服务（指定版本）
# 停止并删除服务：
# docker-compose down 停止服务
#
# 日常启停服务：
# docker-compose start/restart/stop

name: xyzchat

services:
  app:
    image: registry.ware.cloud/xyzchat:${APP_VERSION:-latest}
    container_name: xyzchat-app
    volumes:
        - ./.env:/.env
    ports:
      - 3000:3000
    tty: true
    restart: unless-stopped